### Book Singele Room with Employee authentication

POST {{host}}/book
Authorization: Basic warren.trent@hotel.com {{trent_pass}}
Content-Type: application/json

< content/booking-request-01.json
> test/status-200-json.js

### Book Double Room with Customer authentication

POST {{host}}/book
Authorization: Basic marsha@guest.com {{marsha_pass}}
Content-Type: application/json

{
  "typeId": 2,
  "checkIn": "2022-05-01",
  "checkOut": "2022-05-12"
}
