# Example 1: POST /employee/new request without authentication

POST {{host}}/employee/new
Content-Type: application/json

{
  "name": "Peter McDermott",
  "email": "Peter.McDermott@hotel.com",
  "password": "maNAger02!"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 401, "Response status is not 401 (Deny)");
});
%}

###

#@name RegEmployee_Warren_Trent
# Example 2-1: POST /employee/new request with admin authentication

POST {{host}}/employee/new
Authorization: Basic admin password
Content-Type: application/json

{
  "name": "Warren Trent",
  "email": "warren.trent@hotel.com",
  "password": "{{warren_pass}}"
}

###

# Example 2-2: POST /employee/new request with employee authentication
POST {{host}}/employee/new
Authorization: Basic albert.wells@guest.com ag1ngH0T@Lguest
Content-Type: application/json

{
  "name": "Peter McDermott",
  "email": "Peter.McDermott@hotel.com",
  "password": "{{peter_pass}}"
}

###
# Example 2-2: POST /employee/new request with employee authentication
POST {{host}}/employee/new
Authorization: Basic admin {{admin_pass}}
Content-Type: application/json

{
  "name": "Peter McDermott",
  "email": "Peter.McDermott@hotel.com",
  "password": "{{peter_pass}}"
}

###

# Example 2-3: POST /employee/new request with admin authentication
POST {{host}}/employee/new
Authorization: Basic admin {{admin_pass}}
Content-Type: application/json

{
  "name": "Christine Francis",
  "email": "christine.francis@hotel.com",
  "password": "S@cre+arY01"
}

### Example 3: GET /employee request with admin authentication
GET {{host}}/employee
Authorization: Basic admin@hotel.com {{admin_pass}}

### Example 3-2: GET /employee request with employee authentication
GET {{host}}/employee
Authorization: Basic warren.trent@hotel.com {{warren_pass}}

### Example 3-3: GET /employee request without authentication
GET {{host}}/employee
