INSERT INTO ROOM_TYPE (ID, DESCRIPTION, NAME) VALUES (1, '1 single bed.', 'Single Room');
INSERT INTO ROOM_TYPE (ID, DESCRIPTION, NAME) VALUES (2, '1 large double bed.', 'Double Room');
INSERT INTO ROOM_TYPE (ID, DESCRIPTION, NAME) VALUES (3, '1 extra-large double bed. ', 'Deluxe Double Room');

INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (1, '101', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (2, '102', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (3, '103', 3);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (4, '201', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (5, '202', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (6, '301', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (7, '302', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (8, '303', 3);

