INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (1, '101', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (2, '102', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (3, '103', 3);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (4, '201', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (5, '202', 2);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (6, '301', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (7, '302', 1);
INSERT INTO ROOM (ID, NUMBER, TYPE_ID) VALUES (8, '303', 3);
