#

POST {{host}}/reservation
Authorization: Basic warren.trent@hotel.com {{warren_pass}}
Content-Type: application/json

{
  "typeId": {{SingleRoom}},
  "checkIn": "2022-05-11",
  "checkOut": "2022-05-16"
}

###

POST {{host}}/reservation
Authorization: Basic curtis@guest.com Chain&O57
Content-Type: application/json

{
  "typeId": {{SingleRoom}},
  "checkIn": "2022-05-27",
  "checkOut": "2022-05-29"
}

###

POST {{host}}/reservation
Authorization: Basic albert.wells@guest.com ag1ngH0T@Lguest
Content-Type: application/json

{
  "typeId": {{SingleRoom}},
  "checkIn": "2022-08-22",
  "checkOut": "2022-08-24"
}
###

POST {{host}}/reservation
Authorization: Basic curtis@guest.com Chain&O57
Content-Type: application/json

{
  "typeId": {{DeluxeDoubleRoom}},
  "checkIn": "2022-08-09",
  "checkOut": "2022-08-11"
}

###

POST {{host}}/reservation
Authorization: Basic ogilvie@guest.com Pa55w@Rd
Content-Type: application/json

{
  "typeId": {{DeluxeDoubleRoom}},
  "checkIn": "2022-05-11",
  "checkOut": "2022-05-23"
}

### (1) Double Room reservation

POST {{host}}/reservation
Authorization: Basic Ogilvie@guest.com Pa55w@Rd
Content-Type: application/json

{
  "typeId": {{DoubleRoom}},
  "checkIn": "2022-05-11",
  "checkOut": "2022-05-13"
}

### (2) Double Room reservation

POST {{host}}/reservation
Authorization: Basic curtis@guest.com Chain&O57
Content-Type: application/json

{
  "typeId": {{DoubleRoom}},
  "checkIn": "2022-05-11",
  "checkOut": "2022-05-13"
}

### (3) Double Room reservation

POST {{host}}/reservation
Authorization: Basic albert.wells@guest.com ag1ngH0T@Lguest
Content-Type: application/json

{
  "typeId": 4,
  "checkIn": "2022-07-11",
  "checkOut": "2022-07-13"
}
