#
# Examples of requests to /api/roomTypes
#
# Hotel administrators should be able to manage types of hotel rooms:
# – view
# - add
# - remove
# - edit
#
### should forbid request with no authentication
GET {{host}}/api/roomTypes
Authorization: Basic admin@hotel.com {{admin_pass}}

> test/forbidden.js

### should forbid request with admin authentication
GET {{host}}/api/roomTypes
Authorization: Basic admin@hotel.com {{admin_pass}}

> test/forbidden.js

### List room types (with employee authentication)
GET {{host}}/api/roomTypes
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

> test/successful.js

### Room Type representation profile
GET {{host}}/api/profile/roomTypes
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

### Search options for room types (not found)
GET {{host}}/api/roomTypes/search
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

> test/not-found.js

