#
# Examples of requests to /api/users
#
# Hotel administrators should be able to manage rooms:
# – view
# - add
# - remove
# - edit
#
### Logout
GET {{host}}/logout

### should forbid request with no authentication
GET {{host}}/api/users

> test/forbidden.js

### should forbid request with USER authentication
GET {{host}}/api/users
Authorization: Basic marsha@guest.com {{marsha_pass}}

> test/forbidden.js

### List all users (with employee authentication)
GET {{host}}/api/users
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

> test/successful.js

### User representation profile
GET {{host}}/api/profile/users
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

### Search options
GET {{host}}/api/users/search
Authorization: Basic warren.trent@hotel.com {{trent_pass}}

### Julius "Keycase" Milne, hotel thief

POST {{host}}/api/users
Authorization: Basic warren.trent@hotel.com {{trent_pass}}
Content-Type: application/json

{
  "name": "Julius Milne",
  "email": "keycase@thief.com",
  "password": "x5Yj0@iudTf"
}

### Julius "Keycase" Milne, hotel thief

POST {{host}}/api/users
Authorization: Basic warren.trent@hotel.com {{trent_pass}}
Content-Type: application/json

{
  "name": "Julius Milne",
  "email": "KEYcase@THIEF.com",
  "password": "x5Yj0@iudTf"
}

### delete Julius Milne

DELETE {{host}}/api/users/2
Authorization: Basic warren.trent@hotel.com {{trent_pass}}
