#@name RegCustomer_Albert_Wells
# Example 1: POST /register request without authentication

POST {{host}}/register
Content-Type: application/json

{
  "name": "Albert Wells",
  "email": "albert.wells@guest.com",
  "password": "ag1ngH0T@Lguest"
}

###

