### Check reservation with user authentication
GET {{host}}/reservation/check/?room=6&date=2022-01-22
Authorization: Basic marsha@guest.com MarPrey!09


### Check reservation with employee authentication
GET {{host}}/reservation/check1/?room=6&date=2022-01-22
Authorization: Basic warren.trent@hotel.com {{warren_pass}}

### Check reservation with employee authentication
GET {{host}}/reservation/check2
Authorization: Basic warren.trent@hotel.com {{warren_pass}}
Content-Type: application/json

{
  "room": 5,
  "date": "2022-04-28"
}

### Check reservation with employee authentication
GET {{host}}/reservation/check3
Authorization: Basic warren.trent@hotel.com {{warren_pass}}
Content-Type: application/json

{
  "room": 5,
  "date": "2022-04-28"
}

### Check reservation with employee authentication
GET {{host}}/reservation/check?roomId=6&arrivingDate=2022-01-22&departureDate=2022-02-01
Authorization: Basic warren.trent@hotel.com {{warren_pass}}

