### Add new room with employee authentication

POST {{host}}/room/add
Authorization: Basic Peter.McDermott@hotel.com {{peter_pass}}
Content-Type: application/json

{
  "number": "XXX",
  "description": "Scary room"
}

> {%
client.test("Request executed successfully", () => {
  client.assert(response.status === 200, "Response status is not 200");
  client.global.set("last_id", response.body.id);
});
%}

### List all rooms with employee authentication
GET {{host}}/room
Authorization: Basic warren.trent@hotel.com {{warren_pass}}

### Delete the last added room with employee authentication
DELETE {{host}}/room/{{last_id}}
Authorization: Basic warren.trent@hotel.com {{warren_pass}}
