# Example 1: GET /room request without authentication
GET {{host}}/room
###

# Example 2: GET /room request with admin authentication
GET {{host}}/room
Authorization: Basic admin password
###

# Example 3: GET /room request with user authentication
GET {{host}}/room
Authorization: Basic albert.wells@guest.com ag1ngH0T@Lguest
###

# Example 3: GET /room request with user authentication
GET {{host}}/room
Authorization: Basic warren.trent@hotel.com Pr0pR1et0r!
###


